import { j as e } from "./jsx-runtime.js";
import { r as a } from "./react-runtime.js";
import { c as o } from "./utils.js";
import { m as t } from "./proxy.js";
const l = ["React / Next.js", "TypeScript / JavaScript (ES6+)", "State management (Zustand, Redux, Context)", "Responsive design & accessibility", "Motion & interaction (Framer Motion, GSAP)", "API integration & data fetching", "Node.js / Express / Fastify", "RESTful & GraphQL API design", "PostgreSQL / Prisma ORM", "Authentication & authorization", "WebSockets & real-time systems"], c = [{ company: "Cactus Plant", href: "https://cactusplant.com", role: "Full-stack developer", period: "2024 - Present", skills: [0, 1, 2, 4, 6, 7, 8, 9, 10] }, { company: "Happy Stats", href: "https://happystats.io", role: "Full-stack developer", period: "2023 - 2024", skills: [0, 1, 5, 6, 7, 8, 9] }, { company: "JustOS", href: "https://justos.dev", role: "Frontend developer", period: "2021 - 2023", skills: [0, 1, 2, 3, 4, 5] }, { company: "Freelance", href: "https://upwork.com", role: "Frontend developer", period: "2019 - 2021", skills: [0, 1, 3, 4, 5] }], x = () => {
  const [n, i] = a.useState(null);
  return e.jsxs("section", { className: "section-padding container space-y-10", children: [e.jsx("h2", { className: "text-2xl leading-none", children: "Experience" }), e.jsxs("div", { className: "grid gap-10 md:grid-cols-2", children: [e.jsx("ul", { className: "space-y-10", children: c.map((s) => e.jsx("li", { className: "text-lg leading-none", children: e.jsxs(t.div, { className: "pointer-events-none", initial: "idle", whileHover: "hover", onHoverStart: () => i(s.skills), onHoverEnd: () => i(null), children: [e.jsx(t.div, { className: "pointer-events-auto inline-block", variants: { idle: { x: 0 }, hover: { x: 8 } }, transition: { type: "spring", stiffness: 300, damping: 25 }, children: e.jsx("a", { href: s.href, target: "_blank", rel: "noopener noreferrer", className: "link-underline inline-block", children: s.company }) }), e.jsx(t.p, { className: "text-muted-foreground mt-4", variants: { idle: { x: 0, opacity: 0.7 }, hover: { x: 8, opacity: 1 } }, transition: { type: "spring", stiffness: 300, damping: 25, delay: 0.02 }, children: s.role }), e.jsx(t.p, { className: "text-muted-foreground mt-4", variants: { idle: { x: 0, opacity: 0.7 }, hover: { x: 8, opacity: 1 } }, transition: { type: "spring", stiffness: 300, damping: 25, delay: 0.04 }, children: s.period })] }) }, s.company)) }), e.jsxs("div", { className: "space-y-4 text-lg leading-none", children: [e.jsx("p", { children: "Skills" }), e.jsx("ul", { className: "space-y-4", children: l.map((s, r) => e.jsx("li", { className: o("transition-all duration-300", n === null ? "text-muted-foreground" : n.includes(r) ? "text-foreground" : "text-muted-foreground/40"), children: s }, s)) })] })] })] });
};

export { x as default };
